// Generated by gencpp from file vacuum_cleaner_srv/service1Request.msg
// DO NOT EDIT!


#ifndef VACUUM_CLEANER_SRV_MESSAGE_SERVICE1REQUEST_H
#define VACUUM_CLEANER_SRV_MESSAGE_SERVICE1REQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace vacuum_cleaner_srv
{
template <class ContainerAllocator>
struct service1Request_
{
  typedef service1Request_<ContainerAllocator> Type;

  service1Request_()
    : header()
    , ID_station(0)  {
    }
  service1Request_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , ID_station(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _ID_station_type;
  _ID_station_type ID_station;





  typedef boost::shared_ptr< ::vacuum_cleaner_srv::service1Request_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vacuum_cleaner_srv::service1Request_<ContainerAllocator> const> ConstPtr;

}; // struct service1Request_

typedef ::vacuum_cleaner_srv::service1Request_<std::allocator<void> > service1Request;

typedef boost::shared_ptr< ::vacuum_cleaner_srv::service1Request > service1RequestPtr;
typedef boost::shared_ptr< ::vacuum_cleaner_srv::service1Request const> service1RequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vacuum_cleaner_srv::service1Request_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vacuum_cleaner_srv::service1Request_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vacuum_cleaner_srv::service1Request_<ContainerAllocator1> & lhs, const ::vacuum_cleaner_srv::service1Request_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.ID_station == rhs.ID_station;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vacuum_cleaner_srv::service1Request_<ContainerAllocator1> & lhs, const ::vacuum_cleaner_srv::service1Request_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vacuum_cleaner_srv

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vacuum_cleaner_srv::service1Request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vacuum_cleaner_srv::service1Request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vacuum_cleaner_srv::service1Request_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vacuum_cleaner_srv::service1Request_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vacuum_cleaner_srv::service1Request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vacuum_cleaner_srv::service1Request_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vacuum_cleaner_srv::service1Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c8810e34f23c848d38f05f27209e9b62";
  }

  static const char* value(const ::vacuum_cleaner_srv::service1Request_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc8810e34f23c848dULL;
  static const uint64_t static_value2 = 0x38f05f27209e9b62ULL;
};

template<class ContainerAllocator>
struct DataType< ::vacuum_cleaner_srv::service1Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vacuum_cleaner_srv/service1Request";
  }

  static const char* value(const ::vacuum_cleaner_srv::service1Request_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vacuum_cleaner_srv::service1Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"int32 ID_station\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::vacuum_cleaner_srv::service1Request_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vacuum_cleaner_srv::service1Request_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.ID_station);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct service1Request_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vacuum_cleaner_srv::service1Request_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vacuum_cleaner_srv::service1Request_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "ID_station: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ID_station);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VACUUM_CLEANER_SRV_MESSAGE_SERVICE1REQUEST_H
