// Generated by gencpp from file vacuum_cleaner_srv/service1.msg
// DO NOT EDIT!


#ifndef VACUUM_CLEANER_SRV_MESSAGE_SERVICE1_H
#define VACUUM_CLEANER_SRV_MESSAGE_SERVICE1_H

#include <ros/service_traits.h>


#include <vacuum_cleaner_srv/service1Request.h>
#include <vacuum_cleaner_srv/service1Response.h>


namespace vacuum_cleaner_srv
{

struct service1
{

typedef service1Request Request;
typedef service1Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct service1
} // namespace vacuum_cleaner_srv


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vacuum_cleaner_srv::service1 > {
  static const char* value()
  {
    return "3d13c7504dc3516a51f9bb7e149fa7be";
  }

  static const char* value(const ::vacuum_cleaner_srv::service1&) { return value(); }
};

template<>
struct DataType< ::vacuum_cleaner_srv::service1 > {
  static const char* value()
  {
    return "vacuum_cleaner_srv/service1";
  }

  static const char* value(const ::vacuum_cleaner_srv::service1&) { return value(); }
};


// service_traits::MD5Sum< ::vacuum_cleaner_srv::service1Request> should match
// service_traits::MD5Sum< ::vacuum_cleaner_srv::service1 >
template<>
struct MD5Sum< ::vacuum_cleaner_srv::service1Request>
{
  static const char* value()
  {
    return MD5Sum< ::vacuum_cleaner_srv::service1 >::value();
  }
  static const char* value(const ::vacuum_cleaner_srv::service1Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::vacuum_cleaner_srv::service1Request> should match
// service_traits::DataType< ::vacuum_cleaner_srv::service1 >
template<>
struct DataType< ::vacuum_cleaner_srv::service1Request>
{
  static const char* value()
  {
    return DataType< ::vacuum_cleaner_srv::service1 >::value();
  }
  static const char* value(const ::vacuum_cleaner_srv::service1Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vacuum_cleaner_srv::service1Response> should match
// service_traits::MD5Sum< ::vacuum_cleaner_srv::service1 >
template<>
struct MD5Sum< ::vacuum_cleaner_srv::service1Response>
{
  static const char* value()
  {
    return MD5Sum< ::vacuum_cleaner_srv::service1 >::value();
  }
  static const char* value(const ::vacuum_cleaner_srv::service1Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::vacuum_cleaner_srv::service1Response> should match
// service_traits::DataType< ::vacuum_cleaner_srv::service1 >
template<>
struct DataType< ::vacuum_cleaner_srv::service1Response>
{
  static const char* value()
  {
    return DataType< ::vacuum_cleaner_srv::service1 >::value();
  }
  static const char* value(const ::vacuum_cleaner_srv::service1Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VACUUM_CLEANER_SRV_MESSAGE_SERVICE1_H
